apiVersion: v1
kind: Service
metadata:
  name: python-app-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 8042
      targetPort: 5000
      nodePort: 32260
  type: NodePort