apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-load-balancer-controller-sa
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::055411382616:role/alb-ingress-controller-role