name: Deployment-Workflow-Controller
on:
  workflow_dispatch:

env:
  ROLE_NAME : ${{secrets.ROLE_NAME}}
permissions:
  id-token: write  
  contents: read
jobs:
  HELM_DEPLOY:
    runs-on: ubuntu-latest
    steps:
    - name: Clone Repo
      uses: actions/checkout@main
    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
          role-to-assume: ${{secrets.ROLE_NAME}} 
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: us-east-1
    - name: Helm Deploy
      run: |
           helm repo add eks https://aws.github.io/eks-charts
           helm install aws-load-balancer-controller eks/aws-load-balancer-controller --set clusterName=my-cluster -n kube-system --set serviceAccount.create=false --set serviceAccount.name=aws-load-balancer-controller

